# Generated by Django 2.2 on 2019-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
