# Generated by Django 2.2 on 2019-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_text_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
