# Generated by Django 2.2 on 2019-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_text_text_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_length',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
    ]
