# Generated by Django 2.2 on 2019-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190422_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='default_text',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_length',
        ),
        migrations.AddField(
            model_name='text',
            name='encrypted_text',
            field=models.TextField(default='smth'),
            preserve_default=False,
        ),
    ]
